### ISSUE TITLE
(Optional) Make lines in mermaid graph lighter

### ISSUE THREAD

**Issue by JonMinton** [Public-Health-Scotland/package-dev-guidance-site#21]
I'm wondering if making the lines in the mermaid graph a bit lighter (e.g. a light grey or blue) might make it even easier to read the text. 
Example of restyling [here](https://mermaid.js.org/config/theming.html)

If this is worth doing let me know. If not please just close the issue.

**Comment by alan-y** [comment]
Please go ahead if you think it'll look better. 
I just had a go at launching on gh-pages so we can close the other issue. The only remaining thing for that is maybe to set it up with github Actions - what do you think?

**Comment by JonMinton** [comment]
I've made a change to lightgrey for the line colour. 
There's a known issue with mermaid in that the heads of lines (the arrow parts) don't get updated so will remain black. However this does make the text more readable. 
If the colour mismatch between line colour and arrowhead colour is too distracting then please reject the associated PR
